const FILLER_PREFIXES = [
  'we should',
  'we need to',
  'we want to',
  'can you',
  'could you',
  'would you',
  'i want to',
  "i'd like to",
  'i would like to',
  'i need to',
  "let's",
  'let us',
  'go ahead and',
  'make sure to',
  'try to',
  'you should',
  'you need to',
  'please help me',
  'help me',
  'please',
];

const prefixPattern = new RegExp(
  `^(${FILLER_PREFIXES.map((p) => p.replace(/'/g, "['\u2019]")).join('|')})\\b\\s*`,
  'i',
);

export function cleanTaskName(text: string): string {
  let result = text.trim();

  // Strip leading filler phrases (loop to catch stacked: "please try to ...")
  let prev = '';
  while (result !== prev) {
    prev = result;
    result = result.replace(prefixPattern, '').trim();
  }

  // Strip trailing "please"
  result = result.replace(/\s+please[.!?]?$/i, '').trim();

  return result || text.trim();
}

export const AUTO_TASK_NAME_MAX_LENGTH = 40;
export const DISPLAY_TASK_NAME_MAX_LENGTH = 120;

function firstCleanTaskLine(text: string): string {
  return cleanTaskName(text.trim().split('\n')[0] ?? '');
}

function truncateOnWordBoundary(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;

  const shortened = text.slice(0, maxLength).replace(/\s+\S*$/, '');
  return shortened || text.slice(0, maxLength);
}

export function autoTaskNameFromPrompt(prompt: string): string {
  const trimmed = prompt.trim();
  if (!trimmed) return '';

  return truncateOnWordBoundary(firstCleanTaskLine(trimmed), AUTO_TASK_NAME_MAX_LENGTH);
}

export function displayTaskNameFromPrompt(prompt: string): string {
  const trimmed = prompt.trim();
  if (!trimmed) return '';

  return truncateOnWordBoundary(firstCleanTaskLine(trimmed), DISPLAY_TASK_NAME_MAX_LENGTH);
}

export function isAutoTaskNameFromPrompt(name: string, prompt: string): boolean {
  const trimmedName = name.trim();
  if (!trimmedName) return false;

  const trimmedPrompt = prompt.trim();
  if (!trimmedPrompt) return false;

  const firstLine = firstCleanTaskLine(trimmedPrompt);
  return (
    trimmedName === truncateOnWordBoundary(firstLine, AUTO_TASK_NAME_MAX_LENGTH) ||
    trimmedName === truncateOnWordBoundary(firstLine, 50)
  );
}

const DEFAULT_TASK_NAME_PATTERN = /^Task (\d+)$/;

/**
 * Fallback name for a task created with neither a prompt nor a typed name.
 * Picks the next number above any existing "Task N" so a burst of unnamed
 * tasks gets "Task 1", "Task 2", … instead of all colliding on "Task 1".
 */
export function nextDefaultTaskName(existingNames: string[]): string {
  let max = 0;
  for (const existing of existingNames) {
    const match = DEFAULT_TASK_NAME_PATTERN.exec(existing.trim());
    if (match) max = Math.max(max, parseInt(match[1], 10));
  }
  return `Task ${max + 1}`;
}

export function shouldUsePromptDerivedTaskName(
  name: string,
  prompt: string,
  nameIsAutoGenerated?: boolean,
): boolean {
  if (nameIsAutoGenerated !== undefined) return nameIsAutoGenerated;
  return isAutoTaskNameFromPrompt(name, prompt);
}
